Add imagePullSecrets to streams-app helm chart
bakdata/streams-bootstrap pull request #133
Opened 2022-02-16 14:36 UTC by raminqaf

2022-02-16 14:39 UTC, philipp94831 requested changes
The clean up job needs those as well

2022-02-16 15:28 UTC, yannick-roeder approved these changes

2022-02-17 08:15 UTC, philipp94831 requested changes
Please also add imagePullSecrets to producer charts

2022-02-21 11:01 UTC, philipp94831 approved these changes

2022-02-21 12:07 UTC, merged