Migrate azure pipeline to GH-action
bakdata/streams-bootstrap pull request #191
Opened 2023-10-18 07:39 UTC by MichaelKora

2023-10-20 12:11 UTC, raminqaf approved these changes
Amazing ❤️

2024-02-08 08:56 UTC, philipp94831 requested changes

2024-02-15 18:46 UTC, philipp94831 requested changes

2024-02-15 18:46 UTC, philipp94831 commented on .github/workflows/build-and-publish.yaml
> +    uses: bakdata/ci-templates/.github/workflows/java-gradle-library.yaml@1.40.5
```suggestion
    uses: bakdata/ci-templates/.github/workflows/java-gradle-library.yaml@1.40.6
```

2024-02-15 18:46 UTC, philipp94831 commented on .github/workflows/release.yaml
> +    uses: bakdata/ci-templates/.github/workflows/java-gradle-release.yaml@1.40.5
```suggestion
    uses: bakdata/ci-templates/.github/workflows/java-gradle-release.yaml@1.40.6
```

2024-02-28 15:38 UTC, yannick-roeder approved these changes

2024-02-28 15:39 UTC, philipp94831 approved these changes

2024-02-28 16:06 UTC, merged